import type { Metadata } from 'next'

// context
import { LoadingProvider, ThemeProvider } from '@/contexts'

// global scss
import './globals.scss'
import '@fortawesome/fontawesome-free/css/all.min.css'

// components
import { LoadingRenderer } from './LoadingRenderer'

export const metadata: Metadata = {
  // TODO: set Landing Page's title and description
  metadataBase: new URL('https://www.46ki75.com'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    type: 'website',
    locale: 'ja_JP',
    images: [
      {
        // TODO: set url that Landing Page's OGP image
        url: '',
        width: 1200,
        height: 630
      }
    ]
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ja'>
      <ThemeProvider>
        <LoadingProvider>
          <body>
            {children}
            <LoadingRenderer />
          </body>
        </LoadingProvider>
      </ThemeProvider>
    </html>
  )
}
