import type { Metadata } from 'next'

// global scss
import './globals.scss'

export const metadata: Metadata = {
  // TODO: set Landing Page's title and description
  metadataBase: new URL('https://www.46ki75.com'),
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    type: 'website',
    locale: 'ja_JP',
    images: [
      {
        // TODO: set url that Landing Page's OGP image
        url: '',
        width: 1200,
        height: 630
      }
    ]
  }
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='ja'>
      <body>{children}</body>
    </html>
  )
}
